### PR TITLE
Migrate to multi-target .csproj

### PR DESCRIPTION
**Pull request by stil**
What has been changed:
* Merged .NET Framework and .NET Standard projects into one multitargeting project.
* Merged .nuspec with .csproj
* Tests now can be run with `dotnet test .\Tests\Tests.csproj`

Problems:
*  `DisposeByGCAfterPartialEnumeration` test fails both on .NET Framework and Standard.

### CODE REVIEW

**Comment by slang25** [comment]
@stil nice work. I think `DisposeByGCAfterPartialEnumeration` will only pass when build with Release mode as the GC is more aggressive which is required, is it possible you were running these under Debug mode?

If this is the case, it might be worth making the test conditionally compiled using the attribute:
```csharp
[System.Diagnostics.Conditional("DEBUG")]
```
Or possible better (if you don't mind ifdefs):
```csharp
#if DEBUG
Assert.Inconclusive();
#endif
```

**Comment by stil** [comment]
Thanks @slang25 
You were right, this test requires Release build. Now all tests pass in both frameworks (.NET Standard 1.4 and .NET Framework 4.5).

**Comment by tyrotoxin** [comment]
Thanks for the effort! Please give me some time and get familiar with the changes.

**Comment by Misiu** [comment]
@tyrotoxin any updates on this? Single csproj would be awesome, especially if You want to easy target multiple frameworks.

**Comment by kind-serge** [comment]
@stil, you inspired me to do the right thing (even though I didn't take these changes). Thanks for the contribution!

**Pull request closed without merging**
